initial commit
happy-travel/fukuoka pull request #1
Opened 2020-12-11 09:05 UTC by DFSko

2020-12-11 10:52 UTC, mingazhev approved these changes
Mostly approved, need @kirillta opinion on using records instead of readonly structs

2020-12-11 10:52 UTC, mingazhev commented on HappyTravel.RequestAuditLog/Infrastructure/VaultClientFactory.cs
> +        public static void Login(this IVaultClient client, IConfiguration configuration)
Factory typically only creates something. Maybe rename class to something like Helper

2020-12-11 10:52 UTC, mingazhev commented on HappyTravel.RequestAuditLog/Models/AuditLogEntry.cs
> +    public record AuditLogEntry
HttpRequestAuditLogEntry?

2020-12-11 10:52 UTC, mingazhev commented on HappyTravel.RequestAuditLog/Startup.cs
> +                endpoints.MapHealthChecks("/health");
do healthchecks need authorization?

2020-12-11 13:09 UTC, kirillta requested changes

2020-12-11 13:09 UTC, kirillta commented on HappyTravel.RequestAuditLog/appsettings.json
> +    "Url": "fukuoka/elasticsearch"
We use `Endpoint` across the services

2020-12-13 22:20 UTC, DFSko commented on HappyTravel.RequestAuditLog/Startup.cs
> +                endpoints.MapHealthChecks("/health");
What for? If service can not be accessible from internet it not be needed

2020-12-13 22:51 UTC, DFSko commented on HappyTravel.RequestAuditLog/Infrastructure/VaultClientFactory.cs
> +        public static void Login(this IVaultClient client, IConfiguration configuration)
Fixed

2020-12-13 22:52 UTC, DFSko commented on HappyTravel.RequestAuditLog/Models/AuditLogEntry.cs
> +    public record AuditLogEntry
Fixed

2020-12-13 22:52 UTC, DFSko commented on HappyTravel.RequestAuditLog/Controllers/AuditLogsController.cs
> +        public async Task<ActionResult> AddEntry(LogEntryRequest request, CancellationToken token)
Fixed

2020-12-13 22:52 UTC, DFSko commented on HappyTravel.RequestAuditLog/Models/AuditLogEntry.cs
> +        public int? StatusCode { get; }
Fixed

2020-12-13 22:52 UTC, DFSko commented on HappyTravel.RequestAuditLog/appsettings.json
> +    "Url": "fukuoka/elasticsearch"
Fixed

2020-12-14 08:03 UTC, mingazhev approved these changes
With small comments

2020-12-14 08:04 UTC, mingazhev commented on HappyTravel.RequestAuditLog/Startup.cs
> +                endpoints.MapHealthChecks("/health");
Health checks are mostly needed not for internet but for internal infrastructure dashboards

2020-12-14 08:49 UTC, kirillta approved these changes

2020-12-16 03:21 UTC, DFSko commented on HappyTravel.RequestAuditLog/Infrastructure/ElasticSearchExtension.cs
> +    public static class ElasticSearchExtension
Fixed

2020-12-16 03:22 UTC, DFSko commented on HappyTravel.RequestAuditLog/Models/HttpRequestAuditLogEntry.cs
> +        public string Url { get; init; }
Fixed

2020-12-16 03:31 UTC, merged